### ISSUE TITLE
Diff syntax highlighting is broken with VSCode 1.42.1 + SW 0.1.1

### ISSUE THREAD

**Issue by deftdawg** [robb0wen/synthwave-vscode#106]
Synthwave (v0.0.7) breaks diff syntax highlighting with VSCode 1.38.x.   

(See also: https://github.com/microsoft/vscode/issues/80494)

Love this theme...

**Comment by deftdawg** [comment]
[thanks for breathing life back into this theme, I missed it 😄 ]

Just retested, Diff files don't highlight in Neon Dreams (0.1.1) w/ VS Code 1.42.1.

**Comment by robb0wen** [comment]
Fixed in v0.1.7

**Comment by daniel-liuzzi** [comment]
This should be reopened. I'm on v0.1.8 and the issue still remains.
