### ISSUE TITLE
glow effect is broken after upgrade vscode to v1.45.0

### ISSUE THREAD

**Issue by cache0928** [robb0wen/synthwave-vscode#169]
It seems that glow is broken on vscode v1.45.0. 
I Enable Neon Dreams and restart editor but nothing happened

SynthWave '84 version: 0.1.4
VSCode version: 1.45.0

**Comment by dersnek** [comment]
Sometimes it works for me, sometimes it doesn't.
It seems to work randomly. If I just start VSCode, sometimes it works. If I then choose a folder and open it via UI, all is good. Most of the times it doesn't work.

It seem to work more reliably when I open local Windows folders and almost doesn't work when I open folders via Remote-WSL.

If I try to open VSCode from WSL via `code .`, it won't work. I have to open a new window (sometimes several times), then find that folder via VSCode UI, then it works.

**Comment by Mumeii** [comment]
Brand new user of SynthWave here

Same issue description and same versions used than @cache0928 

Running on Mac

**Comment by 1212087** [comment]
Same error description and VS code version 1.45.0
OS: Linux mint 19.3

**Comment by robb0wen** [comment]
VS code has changed its boot sequence, so the code I've been using to hook into it doesn't always fire at the same time. I'm updating it to use a different approach, which I'll release once I'm sure it is working consistently.

**Comment by robb0wen** [comment]
Pushed a patch to the marketplace. Update and rerun the neon dreams command. It should be working afterwards!

**Comment by sistematico** [comment]
I follow this steps:
![image](https://user-images.githubusercontent.com/97509/109578076-17bbcc80-7acd-11eb-9577-b268251f44d7.png)

And glow still not working for me:
![image](https://user-images.githubusercontent.com/97509/109578186-2e622380-7acd-11eb-908e-e79c810cf7b0.png)

Arch Linux using [visual-studio-code-bin](https://aur.archlinux.org/packages/visual-studio-code-bin) from [AUR](https://aur.archlinux.org).

Thank you in advance.

**Comment by sistematico** [comment]
sudo chown -R lucas:wheel /opt/visual-studio-code/
sudo chmod 775 /opt/visual-studio-code/resources/app/out
Enable Neon Glow
ext install lehni.vscode-fix-checksums
Apply Fix
sudo chown -R root:root /opt/visual-studio-code/

![image](https://user-images.githubusercontent.com/97509/109579155-c280ba80-7ace-11eb-88c0-483213291952.png)

Thank you all.
