### ISSUE TITLE
Blank "What's new in SynthWave '84" opens when starting VSCode

### ISSUE THREAD

**Issue by HydraCOREY** [robb0wen/synthwave-vscode#238]
Issue Type: Bug

Whenever VSCode is opened a tab for "What's new in SynthWave '84" shows up. I tried reinstalling the theme as well as VSCode and the problem persists. I'm also on the latest version which is supposed to fix this.

Extension version: 0.1.9
VS Code version: 1.60.2
OS version: Windows 10 x64 19043.1237

Can provide more information if needed.

**Comment by robb0wen** [comment]
Hmm, that's surprising as the code to open that tab is no longer in the project.  I wonder if something has cached. That said, I've pushed a patch that removes further traces of the page including the markup itself. Hopefully that resolves the issue.

To be sure, please disable neon dreams, deactivate and uninstall the extension and then upgrade to the new version v0.1.10

**Comment by HydraCOREY** [comment]
Very strange, it's still showing up after updating to v0.1.10.
I'm noticing when I deactivate and uninstall, then restart VSCode. It still shows up.
Is there anywhere else it could be getting stored?

**Comment by s-ahuja** [comment]
Even i am getting the same issue, I have uninstalled, and re-installed extension

**Comment by AbdulManaf12** [comment]
Greetings, I have tried my best to remove this and it will be disabled properly. Below i will mentioned all the steps follow them:

1. Go to View --> Command Palette (or for windows CTRL+Shift+P) 
2. Search for: "Preferences: Open Setting (JSON)"
3. Remove below line if there it is:
![image](https://user-images.githubusercontent.com/75582860/177212467-0fee0555-4a76-4db2-b2ee-7453e6a1d8a8.png)
4. Once you have done now uninstall the 
![image](https://user-images.githubusercontent.com/75582860/177212553-78d146f3-1b5b-4978-a35e-02f945df0cc9.png)
5. and this 
![image](https://user-images.githubusercontent.com/75582860/177212594-77ad9937-de26-4720-a205-ab578333e137.png)


I hope once you done all these it works fine.
Thanks
